# Generated by Django 2.2.4 on 2019-09-22 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snippet',
            new_name='SnippetNew',
        ),
    ]
