# Generated by Django 2.2.5 on 2020-08-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0003_snippetnew_black_check_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippetnew',
            name='black_check_number',
            field=models.IntegerField(default=503947156, max_length=100),
        ),
    ]
