# Generated by Django 3.0.10 on 2020-10-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0004_auto_20200827_0145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commitments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('loan', models.CharField(choices=[('one', '$1000'), ('two', '$2000'), ('three', '$3000'), ('four', '$4000'), ('five', '$5000'), ('six', '$6000'), ('seven', '$7000'), ('eight', '$8000')], default='one', max_length=100)),
                ('commitment_date', models.DateField(max_length=500)),
                ('notice', models.CharField(max_length=100)),
            ],
        ),
    ]
