# Generated by Django 3.0.10 on 2020-10-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullbankclose', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullbankclose',
            name='money_return_time',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
