# Generated by Django 4.2.2 on 2023-10-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullbankclose', '0003_auto_20201025_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullbankclose',
            name='comment',
            field=models.CharField(blank=True, default='No comment found', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fullbankclose',
            name='star',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
