# Generated by Django 2.2.5 on 2020-09-21 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='preregisterform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(default='SOME STRING', max_length=500)),
                ('state', models.CharField(blank=True, default='SOME STRING', max_length=100)),
                ('zip_code', models.CharField(default='SOME STRING', max_length=500)),
                ('loan_amount', models.CharField(choices=[('$1000', '$1000 for 12 months = $90.83 each month. (Your total payback to the company would be $1090 with interest rate 9%)'), ('$2000', '$2000 for 24 months = $90.83 each month. (Your total payback to the company would be $2180 with interest rate 9%)'), ('$3000', '$3000 for 36 months = $90.83 each month. (Your total payback to the company would be $3270 with interest rate 9%)'), ('$4000', '$4000 for 48 months = $90.83 each month. (Your total payback to the company would be $4360 with interest rate 9%)'), ('$5000', '$5000 for 60 months = $90.83 each month. (Your total payback to the company would be $5450 with interest rate 9%)'), ('$6000', '$6000 for 72 months = $90.83 each month. (Your total payback to the company would be $6540 with interest rate 9%)'), ('$7000', '$7000 for 84 months = $90.83 each month. (Your total payback to the company would be $7630 with interest rate 9%)'), ('$8000', '$8000 for 96 months = $90.83 each month. (Your total payback to the company would be $8720 with interest rate 9%)')], max_length=100)),
                ('payment_date', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('since_how_long_banking', models.CharField(max_length=100)),
                ('online_banking_status', models.CharField(max_length=100)),
                ('current_balance_in_account', models.CharField(max_length=100)),
            ],
        ),
    ]
