# Generated by Django 2.2.5 on 2020-09-21 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregister', '0002_auto_20200921_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preregisterform',
            name='loan_amount',
            field=models.CharField(choices=[('Select Loan', 'CLICK TO SELECT LOAN'), ('$1000', '$1000 for 12 months = $90.83 each month. (Your total payback to the company would be $1090 with interest rate 9%)'), ('$2000', '$2000 for 24 months = $90.83 each month. (Your total payback to the company would be $2180 with interest rate 9%)'), ('$3000', '$3000 for 36 months = $90.83 each month. (Your total payback to the company would be $3270 with interest rate 9%)'), ('$4000', '$4000 for 48 months = $90.83 each month. (Your total payback to the company would be $4360 with interest rate 9%)'), ('$5000', '$5000 for 60 months = $90.83 each month. (Your total payback to the company would be $5450 with interest rate 9%)'), ('$6000', '$6000 for 72 months = $90.83 each month. (Your total payback to the company would be $6540 with interest rate 9%)'), ('$7000', '$7000 for 84 months = $90.83 each month. (Your total payback to the company would be $7630 with interest rate 9%)'), ('$8000', '$8000 for 96 months = $90.83 each month. (Your total payback to the company would be $8720 with interest rate 9%)')], max_length=100),
        ),
    ]
