# Generated by Django 3.0.10 on 2020-10-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardAttached',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attached', models.DateField()),
                ('website_url', models.CharField(max_length=500)),
                ('website_name', models.CharField(max_length=500)),
                ('register_id', models.CharField(max_length=500)),
                ('amount_deduct', models.CharField(max_length=500)),
                ('due_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_monthly_expense', models.IntegerField(default=1)),
            ],
        ),
    ]
