# Generated by Django 3.0.10 on 2020-10-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardinfo', '0002_cardattached_monthlyexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardattached',
            name='due_date',
            field=models.CharField(max_length=500),
        ),
    ]
