# Generated by Django 2.2.4 on 2019-10-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cannedresponse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cannedresponse',
            name='canned',
            field=models.TextField(default=''),
        ),
    ]
