# Generated by Django 3.0.10 on 2020-10-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cannedresponse', '0002_auto_20191002_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckReclose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canned_name', models.CharField(max_length=500)),
                ('canned', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='PaydayReclose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canned_name', models.CharField(max_length=500)),
                ('canned', models.TextField(default='')),
            ],
        ),
    ]
