# Generated by Django 2.2.5 on 2020-08-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsnew',
            name='black_check_number',
            field=models.IntegerField(default=503947156, max_length=100),
        ),
    ]
