# Generated by Django 2.2.5 on 2020-08-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_subsnew_black_check_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsnew',
            name='amazon_check_number',
            field=models.IntegerField(default=5072595, max_length=100),
        ),
    ]
