# Generated by Django 2.2.5 on 2020-09-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0003_subsnew_amazon_check_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsnew',
            name='diabetes_check_number',
            field=models.IntegerField(default=57045, max_length=100),
        ),
    ]
