# Generated by Django 3.0.10 on 2020-10-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0004_subsnew_diabetes_check_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsnew',
            name='daily_check_created',
            field=models.IntegerField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='subsnew',
            name='daily_collection',
            field=models.IntegerField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='subsnew',
            name='monthly_expense_total',
            field=models.IntegerField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='subsnew',
            name='total_collection',
            field=models.IntegerField(default=1, max_length=100),
        ),
    ]
