# Generated by Django 3.1.13 on 2021-07-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0006_subsnew_treasury_check_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsnew',
            name='scott_check_number',
            field=models.IntegerField(default=517096, max_length=100),
        ),
    ]
