# Generated by Django 3.1.13 on 2021-07-03 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0008_auto_20210703_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subsnew',
            old_name='scott_check_number',
            new_name='scott_new_check_number',
        ),
    ]
