# Generated by Django 3.1.13 on 2021-07-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0009_auto_20210703_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsnew',
            name='final_scott',
            field=models.IntegerField(default=50400395, max_length=100),
        ),
    ]
