# Generated by Django 3.1.13 on 2021-07-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0010_subsnew_final_scott'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsnew',
            name='scott_customer_number',
            field=models.IntegerField(default=17513, max_length=100),
        ),
    ]
