# Generated by Django 4.1.9 on 2023-06-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0012_subsnew_cashier2022_check_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsnew',
            name='cashier2022_check_number',
            field=models.IntegerField(default=2469500, max_length=100),
        ),
    ]
