# Generated by Django 4.2.2 on 2023-07-16 12:05

from django.db import migrations, models
import subscribe.models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0015_subsnew_personal_check_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsnew',
            name='image',
            field=models.ImageField(default=1, storage=subscribe.models.OverwriteStorage(), upload_to=''),
        ),
        migrations.AddField(
            model_name='subsnew',
            name='personal_account_number',
            field=models.IntegerField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='subsnew',
            name='personal_check_address',
            field=models.CharField(default=1, max_length=1000),
        ),
        migrations.AddField(
            model_name='subsnew',
            name='personal_check_city_state_zip_code',
            field=models.CharField(default=1, max_length=1000),
        ),
        migrations.AddField(
            model_name='subsnew',
            name='personal_check_full_name',
            field=models.CharField(default=1, max_length=1000),
        ),
        migrations.AddField(
            model_name='subsnew',
            name='personal_routing_number',
            field=models.IntegerField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='subsnew',
            name='personal_small_text',
            field=models.CharField(default=1, max_length=1000),
        ),
        migrations.AlterField(
            model_name='subsnew',
            name='personal_check_number',
            field=models.IntegerField(default=1, max_length=100),
        ),
    ]
