# Generated by Django 4.2.2 on 2023-07-16 12:06

from django.db import migrations, models
import subscribe.models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0016_subsnew_image_subsnew_personal_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsnew',
            name='image',
            field=models.ImageField(storage=subscribe.models.OverwriteStorage(), upload_to=''),
        ),
    ]
