# Generated by Django 4.2.2 on 2023-07-16 12:14

from django.db import migrations, models
import subscribe.models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0017_alter_subsnew_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsnew',
            name='image',
            field=models.ImageField(default='test', storage=subscribe.models.OverwriteStorage(), upload_to=''),
        ),
    ]
