# Generated by Django 4.2.2 on 2023-09-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0018_alter_subsnew_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsnew',
            name='personal_account_number',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='subsnew',
            name='personal_check_number',
            field=models.CharField(default=2, max_length=100),
        ),
        migrations.AlterField(
            model_name='subsnew',
            name='personal_routing_number',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
