# Generated by Django 4.2.2 on 2023-10-04 20:44

from django.db import migrations, models
import subscribe.models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0019_alter_subsnew_personal_account_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='businessCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_image_name', models.CharField(default='test', max_length=100)),
                ('image', models.ImageField(default='test', storage=subscribe.models.OverwriteStoragebusinesscheck(), upload_to='')),
                ('business_check_number', models.CharField(default=2, max_length=100)),
                ('business_account_number', models.CharField(default=1, max_length=100)),
                ('business_routing_number', models.CharField(default=1, max_length=100)),
                ('business_check_company_name', models.CharField(default=1, max_length=1000)),
                ('business_check_address', models.CharField(default=1, max_length=1000)),
                ('business_check_city_state_zip_code', models.CharField(default=1, max_length=1000)),
                ('business_small_text', models.CharField(blank=True, max_length=1000, null=True)),
                ('business_small_text_2', models.CharField(blank=True, max_length=1000, null=True)),
                ('issued_bank_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('issued_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('issued_city_state_zipcode', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
