# Generated by Django 4.2.2 on 2023-10-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0020_businesscheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscheck',
            name='business_check_second_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='businesscheck',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subsnew',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subsnew',
            name='personal_check_second_full_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='subsnew',
            name='personal_small_text_2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
