# Generated by Django 2.2.4 on 2019-09-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('comment', models.CharField(default='Thanks for the loan', max_length=5000)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
