# Generated by Django 2.2.6 on 2020-01-20 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentarea', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='posted_at',
        ),
    ]
