# Generated by Django 3.1.13 on 2021-07-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentarea', '0002_remove_comments_posted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='cashappcomments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('comment', models.CharField(default='Thanks for the loan', max_length=5000)),
            ],
        ),
    ]
