# Generated by Django 4.1.9 on 2023-06-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentarea', '0003_cashappcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date_posted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
