# Generated by Django 2.2.5 on 2020-02-18 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoclose', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SnippetNewOne',
            new_name='autoclosesnippet',
        ),
    ]
