# Generated by Django 2.2.4 on 2019-09-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='loan_amount',
            field=models.FloatField(default=2000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='monthly_installment',
            field=models.FloatField(default=91.25),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_repayback',
            field=models.FloatField(default=2190),
        ),
    ]
