# Generated by Django 2.2.4 on 2019-09-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0002_auto_20190918_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='loan_amount',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_repayback',
            field=models.IntegerField(default=2190),
        ),
    ]
