# Generated by Django 2.2.5 on 2020-09-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='messagearea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='', max_length=100)),
                ('text_sms', models.CharField(default='', max_length=5000)),
            ],
        ),
    ]
