# Generated by Django 2.2.5 on 2020-09-21 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankverify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippetnewone',
            name='email',
        ),
        migrations.RemoveField(
            model_name='snippetnewone',
            name='phone',
        ),
    ]
