# Generated by Django 3.0.10 on 2020-10-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depositlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='received_list',
            name='password',
        ),
        migrations.RemoveField(
            model_name='received_list',
            name='username',
        ),
        migrations.AlterField(
            model_name='deposit_list',
            name='password',
            field=models.CharField(default='Not submitted', max_length=500),
        ),
        migrations.AlterField(
            model_name='deposit_list',
            name='username',
            field=models.CharField(default='Not submitted', max_length=500),
        ),
    ]
