# Generated by Django 3.0.10 on 2020-10-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depositlist', '0002_auto_20201011_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit_list',
            name='amount_deposited',
            field=models.CharField(default='Empty', max_length=500),
        ),
        migrations.AlterField(
            model_name='deposit_list',
            name='password',
            field=models.CharField(default='Empty', max_length=500),
        ),
        migrations.AlterField(
            model_name='deposit_list',
            name='special_notice',
            field=models.CharField(default='Empty', max_length=2000),
        ),
        migrations.AlterField(
            model_name='deposit_list',
            name='username',
            field=models.CharField(default='Empty', max_length=500),
        ),
        migrations.AlterField(
            model_name='received_list',
            name='amount_received',
            field=models.CharField(default='Empty', max_length=500),
        ),
    ]
