# Generated by Django 3.0.10 on 2020-10-31 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depositlist', '0003_auto_20201025_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='received_list',
            name='password',
            field=models.CharField(default='Empty', max_length=500),
        ),
        migrations.AddField(
            model_name='received_list',
            name='username',
            field=models.CharField(default='Empty', max_length=500),
        ),
        migrations.AlterField(
            model_name='deposit_list',
            name='amount_deposited',
            field=models.CharField(default='720 Default', max_length=500),
        ),
        migrations.AlterField(
            model_name='deposit_list',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
