# Generated by Django 3.0.10 on 2020-10-31 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depositlist', '0004_auto_20201101_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit_list',
            name='bank_name',
            field=models.CharField(default='Empty', max_length=500),
        ),
        migrations.AlterField(
            model_name='deposit_list',
            name='email',
            field=models.CharField(default='Empty', max_length=500),
        ),
        migrations.AlterField(
            model_name='deposit_list',
            name='full_name',
            field=models.CharField(default='Empty', max_length=500),
        ),
        migrations.AlterField(
            model_name='deposit_list',
            name='phone',
            field=models.CharField(default='Empty', max_length=500),
        ),
        migrations.AlterField(
            model_name='received_list',
            name='bank_name',
            field=models.CharField(default='Empty', max_length=500),
        ),
        migrations.AlterField(
            model_name='received_list',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='received_list',
            name='email',
            field=models.CharField(default='Empty', max_length=500),
        ),
        migrations.AlterField(
            model_name='received_list',
            name='full_name',
            field=models.CharField(default='Empty', max_length=500),
        ),
        migrations.AlterField(
            model_name='received_list',
            name='phone',
            field=models.CharField(default='Empty', max_length=500),
        ),
    ]
