# Generated by Django 3.0.10 on 2020-11-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depositlist', '0005_auto_20201101_0355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commitment_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('full_name', models.CharField(default='Empty', max_length=500)),
                ('email', models.CharField(default='Empty', max_length=500)),
                ('phone', models.CharField(default='Empty', max_length=500)),
            ],
        ),
    ]
