# Generated by Django 3.0.10 on 2020-11-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depositlist', '0006_commitment_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment_list',
            name='pay_date',
            field=models.CharField(default='Empty', max_length=500),
        ),
    ]
