# Generated by Django 3.0.10 on 2020-11-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depositlist', '0007_commitment_list_pay_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit_list',
            name='closed_by',
            field=models.CharField(default='Captain', max_length=2000),
        ),
    ]
