# Generated by Django 3.1.13 on 2021-07-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depositlist', '0008_deposit_list_closed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit_list',
            name='ultimate_form_id',
            field=models.CharField(default='Test', max_length=2000),
        ),
    ]
