# Generated by Django 3.1.13 on 2021-07-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depositlist', '0009_deposit_list_ultimate_form_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commitment_Create',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('full_name', models.CharField(default='Empty', max_length=500)),
                ('email', models.CharField(default='Empty', max_length=500)),
                ('phone', models.CharField(default='Empty', max_length=500)),
                ('pay_date', models.CharField(default='Empty', max_length=500)),
                ('date_to_show_balance', models.DateField(default='Empty', max_length=500)),
            ],
        ),
    ]
