# Generated by Django 2.2.6 on 2020-01-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CannedResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reclose_name', models.CharField(max_length=500)),
                ('reclose_area', models.TextField(default='')),
            ],
        ),
    ]
