# Generated by Django 2.2.6 on 2020-01-20 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclose', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CannedResponse',
            new_name='RecloseResponse',
        ),
    ]
