# Generated by Django 3.0.7 on 2020-07-19 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullcheckinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SnippetNewOne',
            new_name='bankverificationform',
        ),
    ]
