# Generated by Django 3.0.7 on 2020-07-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullcheckinfo', '0002_auto_20200719_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankverificationform',
            name='status',
            field=models.CharField(blank=True, default='SOME STRING', max_length=100),
        ),
    ]
