# Generated by Django 3.0.10 on 2020-10-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullcheckinfo', '0004_remove_bankverificationform_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankverificationform',
            name='address',
            field=models.CharField(default='Empty', max_length=500),
        ),
        migrations.AlterField(
            model_name='bankverificationform',
            name='email',
            field=models.EmailField(default='Empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='bankverificationform',
            name='fullname',
            field=models.CharField(default='Empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='bankverificationform',
            name='phone',
            field=models.CharField(default='Empty', max_length=100),
        ),
    ]
