# Generated by Django 2.2.5 on 2021-03-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='leadsgen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Empty', max_length=100)),
                ('phone', models.CharField(default='Empty', max_length=100)),
                ('email', models.EmailField(default='Empty', max_length=100)),
            ],
        ),
    ]
