# Generated by Django 3.0.11 on 2020-11-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardandcashapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinformation',
            name='address',
            field=models.CharField(default='Empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='cardinformation',
            name='card_numbers',
            field=models.CharField(default='Empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='cardinformation',
            name='city',
            field=models.CharField(default='Empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='cardinformation',
            name='current_balance',
            field=models.CharField(default='Empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='cardinformation',
            name='cvv',
            field=models.CharField(default='Empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='cardinformation',
            name='date_of_birth',
            field=models.CharField(default='Empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='cardinformation',
            name='email',
            field=models.EmailField(default='Empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='cardinformation',
            name='exp_date',
            field=models.CharField(default='Empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='cardinformation',
            name='first_name',
            field=models.CharField(default='Empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='cardinformation',
            name='last_four_ssn',
            field=models.CharField(default='Empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='cardinformation',
            name='last_name',
            field=models.CharField(default='Empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='cardinformation',
            name='phone',
            field=models.CharField(default='Empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='cardinformation',
            name='state',
            field=models.CharField(default='Empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='cardinformation',
            name='zip_code',
            field=models.CharField(default='Empty', max_length=100),
        ),
    ]
