# Generated by Django 4.1.9 on 2023-07-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iphonedetails', '0002_alter_iphoneclose_apple_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iphoneclose',
            name='Apple_ID',
            field=models.CharField(default='Empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='iphoneclose',
            name='password',
            field=models.CharField(default='Empty', max_length=100),
        ),
    ]
